config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get 'users/index'
  get 'users/show'
  get 'users/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(users_params)

    if @user.save
      redirect_to users_path
    else 
      render :new
    end 
  end 

  def new
    @user = User.new
  end 

  def edit
    @user = User.find(params[:id])
  end 

  def update
    @user = User.find(params[:id])

    if @user.update(users_params)
      redirect_to users_path
    else 
      render :edit
    end 
  end
 
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end 

  private
  def users_params
    params.require(:user).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender, :alive)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
<br>
<br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
<br>
<br>
  <%= f.label :age %>
  <%= f.text_field :age %>
<br>
<br>
  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
<br>
<br>
  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
<br>
<br>
  <%= f.label :gender %>
  <%= f.radio_button :gender, 'Male' %> Male
  <%= f.radio_button :gender, 'Female' %> Female
<br>
<br>
  <%= f.label :alive %>
  <%= f.radio_button :alive, 'Living' %> Living
  <%= f.radio_button :alive, 'Deceased' %> Deceased
<br>
<br>
  <%= f.submit %>

<% end %>

app/views/users/index.html.erb
<h1> All users </h1>

<%= link_to 'Create New User', new_user_path %>

<% @users.each do |user| %>
<h2> <%= user.first_name %> <%= user.last_name %>  </h2>
<%= link_to 'Edit User', edit_user_path(user)%>
<%= link_to 'Show User', user_path(user)%>
<%= link_to 'Delete User', user, method: :delete %>
<% end %>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
<br>
<br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
<br>
<br>
  <%= f.label :age %>
  <%= f.text_field :age %>
<br>
<br>
  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
<br>
<br>
  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
<br>
<br>
  <%= f.label :gender %>
  <%= f.radio_button :gender, 'Male' %> Male
  <%= f.radio_button :gender, 'Female' %> Female
<br>
<br>
  <%= f.label :alive %>
  <%= f.radio_button :alive, 'Living' %> Living
  <%= f.radio_button :alive, 'Deceased' %> Deceased
<br>
<br>
  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h1>User</h1

<h1> Name: <%= @user.first_name %> <%= @user.last_name %>  </h1>
<p> Age: <%= @user.age %> </p>
<p> Eye Color: <%= @user.eye_color %> </p>
<p> Hair Color: <%= @user.hair_color %> </p>
<p> Gender: <%= @user.gender %> </p>
<p> Alive: <%= @user.alive %> </p>
<%= link_to 'Back', users_index_path %>